name: Release
on:
  release:
    types:
      - published
jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Build amd64
        run: go build -ldflags="-s -w" -trimpath -o "build/ogp-${GOARCH}_${RUNNER_OS}" src/main.go
        env:
          GOARCH: amd64
      - name: Build arm64
        run: go build -ldflags="-s -w" -trimpath -o "build/ogp-${GOARCH}_${RUNNER_OS}" src/main.go
        env:
          GOARCH: arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/ogp*
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
